spring:
  application:
    name: ecommerce
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_mvc_db
    username: root
    password: Usef@123456
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  port: 8282
  

keycloak:
  realm: "keycloak-angular"
  auth-server-url: "http://127.0.0.1:9191/"
  resource: "mi-application-angular"
  public-client: true
 